import type { Metadata } from "next";
import { Geist, Geist_Mono, Noto_Serif_Bengali } from "next/font/google";
import "./globals.css";
import Header from "@/componants/Header";
import Footer from "@/componants/Footer";
import Marquee from "@/app/(protected)/Marquee";
import { Toaster } from "react-hot-toast";

const notoSerifBangali = Noto_Serif_Bengali({
  subsets: ["latin", "bengali"],
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      data-theme="light"
      className={`${notoSerifBangali.className} ${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Header />
        <Marquee />
        <main className="bg-[#F0F5F0]">
          <Toaster
            position="top-center"
            reverseOrder={false}
            containerStyle={{
              top: 8, // below your fixed header
              zIndex: 99999,
            }}
            toastOptions={{
              duration: 5000,
              style: {
                background: "#ffffff",
                color: "#202923",
                border: "1px solid #e5e7eb",
                borderRadius: "12px",
                zIndex: 99999,
                padding: "14px 16px",
                fontSize: "14px",
              },
              success: {
                iconTheme: {
                  primary: "#008744",
                  secondary: "#ffffff",
                },
              },
            }}
          />
          
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
